# Generated by Django 3.0.6 on 2020-10-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('source_id', models.IntegerField()),
                ('source_name', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('website', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=32)),
                ('adress', models.CharField(max_length=32)),
                ('postal_code', models.FloatField()),
                ('city', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=32)),
            ],
        ),
    ]
