# Generated by Django 3.0.6 on 2020-10-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201011_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('left_company_id', models.IntegerField()),
                ('right_company_id', models.IntegerField()),
            ],
        ),
    ]
