# Generated by Django 3.0.6 on 2020-10-12 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201013_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='_company_id',
            new_name='right_company_id',
        ),
    ]
