# Generated by Django 3.0.6 on 2020-10-16 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201013_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='postal_code',
            field=models.CharField(max_length=256),
        ),
    ]
