# Generated by Django 3.0.6 on 2020-10-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201017_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='name',
            field=models.CharField(default='null', max_length=256),
        ),
    ]
