# Generated by Django 3.0.6 on 2020-10-16 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_match_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='name',
        ),
    ]
